
<?php if ($this->isPossibleOnepageCheckout()):?>
<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="jQuery('.dt-quick-checkout').toggle(200);"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
<?php endif?>
